channels:
    - conda-forge
dependencies:
    - python=3.12

    - mamba
    - pip
    - ruff

    - jupyter

    - numpy=2.2
    - scipy=1.14
    - pandas=2.2
    - tqdm
    - python-dotenv

    - typer
    - loguru

    - scikit-learn=1.6
    - pymatgen=2024.10.29

    - matplotlib=3.9
    - seaborn=0.13

    - graphviz=12.0
    - python-graphviz=0.20
